name: Build and Push Docker Images

on:
  push:
    branches: [main, develop]
    tags: ['v*']
  pull_request:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        component:
          - name: mcp-server
            dockerfile: Dockerfile
            context: .
          - name: mcp-python
            dockerfile: containers/languages/Dockerfile.python
            context: containers/languages
          - name: mcp-node
            dockerfile: containers/languages/Dockerfile.node
            context: containers/languages
          - name: mcp-vscode
            dockerfile: containers/vscode/Dockerfile
            context: containers/vscode
          - name: mcp-playwright
            dockerfile: containers/playwright/Dockerfile
            context: containers/playwright

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ matrix.component.name }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.component.context }}
          file: ${{ matrix.component.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64

  build-complete:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Summary
        run: |
          echo "🎉 All Docker images built and pushed successfully!"
          echo "📦 Available images:"
          echo "- ghcr.io/${{ github.repository }}/mcp-server:latest"
          echo "- ghcr.io/${{ github.repository }}/mcp-python:latest"  
          echo "- ghcr.io/${{ github.repository }}/mcp-node:latest"
          echo "- ghcr.io/${{ github.repository }}/mcp-vscode:latest"
          echo "- ghcr.io/${{ github.repository }}/mcp-playwright:latest"
